vite.config.ts
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- base isDevMode 삭제
resolves #7
=> [MERGE] : vercel 배포 과정 중 오류 수정

index.html
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- icon 빈줄 삭제
resolves #7
=> [MERGE] : icon 빈줄로 인한 오류 수정

index.html, vite.config.ts
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #5
=> [MERGE] : 배포 테스트를 위한 main 병합

src/components/ProblemCardTag/ProblemCardTag.module.css, src/components/ProblemCardTag/ProblemCardTag.tsx
- 기능은 카드 컴포넌트에만 있어서 부가적인 기능 구현X
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #19
=> [MERGE] : 카드 컴포넌트에 사용될 태그 제작 후 병합

src/styles/Main.css
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- CSS 변수 추가
- sr-only
- large-2 : 1.5rem(24px)
resolves #22
=> [MERGE] : CSS 변수 추가 및 병합

src/styles/Main.css
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- radius에 관련된 css 변수 추가
- 2xl , 3xl , full
resolves #25
=> [MERGE] : radius에 관련된 css 변수 추가

src/components/Input/Input.module.css, src/components/Input/Input.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- input 컴포넌트 작성
resolves #16
=> [MERGE] : input 컴포넌트

src/components/SelectTag/SelectTag.module.css, src/components/SelectTag/SelectTag.tsx, src/components/SelectTag/Tag.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 문제 생성 혹은 문제 목록 페이지에서 사용되는 태그 선택 컴포넌트
- 상태 관리는 부모 영역에서 관리 
- 이후 페이지 결합 과정에서 zustand로 상태관리 변경 예정
resolves #17
=> [MERGE] : 태그 선택 컴포넌트 develop 브랜치 병합

src/components/Option/Option.module.css, src/components/Option/Option.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 문제풀이 페이지의 선지 컴포넌트 구현
resolves #24
=> [MERGE] : 선지 컴포넌트 develop 브랜치로 병합

src/components/ProgressBar/ProgressBar.module.css, src/components/ProgressBar/ProgressBar.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 전체 문제 수, 현재 문제 번호
- 프로그레스 바
resolves #35
=> [FEAT] : 프로그레스 섹션 구현

src/components/Question/Question.module.css, src/components/Question/Question.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #16
=> [MERGE] : components/question 병합

src/components/RoundeButton/RoundedButton.module.css, src/components/RoundeButton/RoundedButton.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 기존의 버튼과 스타일링이 다른 버튼 제작
- 폰트,크기,배경 색상 지정 가능
resolves #44
=> [MERGE] : 둥근 모양의 버튼 컴포넌트 제작 후 병합

src/components/Comment/Comment.module.css, src/components/Comment/Comment.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
문제 풀이 완료 페이지의 댓글 컴포넌트 구현
resolves #48
=> [FEAT] : 댓글 컴포넌트 제작

src/components/RoundeButton/RoundedButton.module.css, src/components/RoundeButton/RoundedButton.tsx, src/layout/Header/Header.module.css, src/layout/Header/Header.tsx, src/layout/Header/components/HeaderSearchBar.tsx, src/layout/Header/components/LoggedIn.tsx, src/layout/Header/components/LoggedOut.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 헤더 컴포넌트 제작 후 develop 브랜치에 병합
- 유저 정보에 따른 UI
resolves #37
=> [MERGE] : Header컴포넌트 병합

src/components/Modal/ModalLayout.module.css, src/components/ProblemCardModal/ProblemCardModal.module.css
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
단위 px에서 rem으로 수정
위치 잘못 조정된 부분 마진값 수정
resolves #64
=> 모달창 단위 px -> rem으로 수정했습니다.

src/components/MyPageTab/MyPageTab.module.css, src/components/MyPageTab/MyPageTab.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #58
=> [FEAT] : 책갈피 컴포넌트 제작

src/components/Button/Button.tsx, src/components/MyPageDiary/MyPageDiary.module.css, src/components/MyPageDiary/MyPageDiary.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- mypage에 존재하는 다이어리 형태의 UI 구현
- 현재 링크에 따라 버튼의 색상 조정
resolves #60
=> [MERGE] : 다이어리 기본 틀 컴포넌트 제작

src/components/Input/Input.module.css, src/lib/schema.ts, src/pages/SignUp/components/SignUpForm.module.css, src/pages/SignUp/components/SignUpForm.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 회원가입페이지 css제작
- 추후 버튼 css 위치조정 필요
resolves #73
=> [MERGE] : 회원가입페이지 CSS 제작

src/components/Input/Input.tsx
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #87
=> [FIX] : input.tsx module 경로 변경

src/App.tsx
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #87
=> [FIX] : basename 삭제

src/layout/Header/Header.module.css, src/layout/Header/Header.tsx, src/layout/Header/components/LoggedOut.tsx
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #87
=> [MERGE] : 배포테스트 준비

src/pages/FindId/Page.tsx, src/pages/FindId/components/FindId.module.css, src/pages/FindId/components/FindId.tsx, src/pages/LogIn/components/LogIn.tsx
- [] 버그 수정
- [] 코드 리팩토링
- id찾기 기능 구현
- loginPage id찾기 | pw찾기 경로 변경
resolves #94
=> [FEAT] : 아이디찾기 페이지

src/lib/schema.ts, src/pages/LogIn/components/LogIn.tsx, src/pages/SignUp/components/SignUpForm.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
resolves #97
=> [CHORE] : supabase table 변경

package.json, pnpm-lock.yaml, src/components/EditProfile/EditProfile.module.css, src/components/EditProfile/EditProfile.tsx, src/components/EditProfile/EmailAlarm.module.css, src/components/EditProfile/EmailAlarm.tsx, src/components/EditProfile/ProfileImage.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
개인 정보 관리 폼(사진 + 인풋들) 컴포넌트 제작
resolves #79
=> [FEAT] 개인 정보 관리 컴포넌트 제작

index.html, src/components/RoundedButton/RoundedButton.tsx, src/layout/Header/Header.module.css, src/layout/Header/Header.tsx, src/layout/Header/components/HeaderSearchBar.module.css, src/layout/Header/components/HeaderSearchBar.tsx, vite.config.ts
- [] 새로운 기능 추가
- [] 문서 수정
- module.css가 배포환경에서 정상적으로 적용이 되지 않던 오류 해결
- vite.config.js로 module.css className 관리
- 우선순위 고려 후 재조정
resolves #99
=> [MERGE] : RoundedButton 컴포넌트 수정과  Header 디자인 오류 수정

src/pages/FindId/components/FindId.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
resolves #103
=> [CHORE] : findId data들고 오는 table 변경

src/App.tsx, src/components/CardSwiper/CardSwiper.module.css, src/components/CardSwiper/CardSwiper.tsx, src/components/ProblemCard/BookMark.tsx, src/components/ProblemCard/ProblemCard.module.css, src/components/ProblemCard/ProblemCard.tsx, src/components/ProblemCardModal/ProblemCardModal.module.css, src/components/ProblemCardModal/ProblemCardModal.tsx, src/lib/ProblemModalState.tsx, src/pages/Main/Page.tsx, src/pages/SolveProblem/Page.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 문제 카드 - 팝업 컴포넌트 연결
- 문제 카드에서 풀이 버튼 클릭 시 링크 이동 
- 문제 id에 따라 페이지가 다르게 나타나도록 설정
- searchParams이용
- zustand를 이용한 유저가 선택한 문제 상태 저장
resolves #105
=> [MERGE] : 문제 카드 컴포넌트 - 팝업 컴포넌트 연결 및 문제풀이 페이지 링크 추가

src/App.tsx, src/components/MyPageDiary/MyPageDiary.tsx, src/components/ProblemGrid/ProblemGrid.module.css, src/components/ProblemGrid/ProblemGrid.tsx, src/pages/Bookmark/Page.module.css, src/pages/Bookmark/Page.tsx, src/pages/Calendar/Page.module.css, src/pages/Calendar/Page.tsx, src/pages/CardCollection/Page.module.css, src/pages/CardCollection/Page.tsx, src/pages/RecentView/Page.module.css, src/pages/RecentView/Page.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
마이페이지의 라이브러리 쪽 페이지 3개 제작
북마크 페이지, 최근 본 카드 페이지, 작성글 페이지.
아직, 탭에 이동 링크 넣는 기능은 완성 못함. 따로 브렌치를 팔 예정.
마이페이지 레이아웃이 화면이 가로로 좁아졌을 때 카드가 빠져나오는 것도 따로 브렌치를 팔 예정.
resolves #107
=> 마이페이지 라이브러리 쪽 페이지 3개

src/components/CardSwiper/CardSwiper.tsx, src/components/ProblemCard/ProblemCard.tsx, src/lib/ProblemModalState.tsx, src/pages/Main/Page.tsx, src/pages/SolveProblem/Page.tsx
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
- 문제 카드에서 모달창으로 description 전달
- userInfo 에서 cardInfo로 변수명 통일
resolves #109
=> [MERGE] : 문제 풀이 링크로 연결하는 과정 중 desc 누락 해결

src/components/ProblemCardModal/ProblemCardModal.module.css, src/components/ProblemGrid/ProblemGrid.module.css, src/components/ProblemGrid/ProblemGrid.tsx, src/pages/Bookmark/Page.tsx, src/pages/CardCollection/Page.tsx, src/pages/Main/Page.tsx, src/pages/ProblemList/components/ProblemListContainer.module.css, src/pages/ProblemList/components/ProblemListContainer.tsx, src/pages/RecentView/Page.tsx
- [] 버그 수정
- [] 문서 수정
- 북마크, 최근본, 작성한 카드를 모아놓은 마이페이지에서 모달연결
- 문제 목록 페이지에서 모달 연결
- 메인 페이지의 타입 지정 변경
resolves #115
=> [MERGE] : 문제 카드 컴포넌트와 모달 컴포넌트를 여러 페이지에서 연결

src/components/Comment/Comment.module.css, src/components/CommentList/CommentList.module.css, src/components/CommentList/CommentList.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #83
=> [FEAT] : 댓글 목록 컴포넌트 제작

src/App.tsx, src/pages/ProblemSolved/Page.module.css, src/pages/ProblemSolved/Page.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> [FEAT] : 문제 풀이 완료 페이지 컴포넌트 배치

src/components/EditProfile/EditProfile.module.css, src/components/EditProfile/EditProfile.tsx, src/components/EditProfile/ProfileImage.tsx, src/components/MyPageDiary/MyPageDiary.tsx, src/pages/EditProfile/components/EditProfileContainer.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- NavLink 개인정보 관리 페이지 URL 변경
- className 변경
resolves #134
=> [MODIFY] : 개인정보 관리 페이지 URL 변경

vercel.json
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #130
=> [FIX] : 배포 시 url 이동 삭제된 코드 복구

vercel.json
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #137
=> [MODIFY] : vercel 배포에 실패한 이유인 source 문법 수정

backend/server.js
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #139
=> [MODIFY] :  origin 개발환경, 서버환경 분리

src/components/Input/Input.module.css, src/pages/SignUp/components/SignUpForm.module.css
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #140
=> [DESIGN] : sign-up CSS 수정

src/components/Calendar/Calendar.tsx, src/components/CardSwiper/CardSwiper.module.css, src/components/CardSwiper/CardSwiper.tsx, src/components/MyPageDiary/MyPageDiary.tsx, src/components/MyPageTab/MyPageTab.tsx, src/pages/ProblemList/components/ProblemListContainer.module.css, src/pages/ProblemList/components/ProblemListContainer.tsx
- [] 버그 수정
- [] 문서 수정
[목록 페이지]
정렬 기준 중 '추천순'을 '최신순'으로 수정
fetch 위치 관련 중간점검 피드백 반영
스켈레톤 느낌으로 카드가 0개인 경우 '카드가 없습니다'라는 문구 뜨도록 하기.
[마이페이지]
달력 요일을 일-월화수목금-토 순서로 수정
resolves #142
=> 목록 페이지 피드백 반영 코드 수정 

src/App.tsx, src/components/Card/Card.tsx, src/components/CardGrid/CardGrid.tsx, src/components/CardSwiper/CardSwiper.tsx, src/components/Option/Option.module.css, src/components/Option/Option.tsx, src/components/RoundedButton/RoundedButton.module.css, src/lib/ProblemModalState.tsx, src/lib/QuizSolvedState.tsx, src/lib/ResetState.tsx, src/pages/Bookmark/Page.tsx, src/pages/CardWritten/Page.tsx, src/pages/Main/Page.tsx, src/pages/QuizPlay/Page.tsx, src/pages/QuizPlay/components/Quiz.module.css, src/pages/QuizPlay/components/Quiz.tsx, src/pages/RecentView/Page.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 문제풀이 페이지 구현
- zustand로 상태 관리
- 현재 문제 풀이 완료 페이지는 문제 아이디를 사용해서 연결
resolves #129
=> [MERGE] : 문제 풀이 페이지 구현

package.json, pnpm-lock.yaml, src/components/CardModal/CardModal.tsx, src/layout/Footer/Footer.module.css, src/layout/Footer/Footer.tsx, src/layout/Header/Header.module.css, src/layout/Header/Header.tsx, src/layout/Header/components/HeaderSearchBar.tsx, src/layout/Header/components/LoggedIn.module.css, src/layout/Header/components/LoggedIn.tsx, src/layout/Header/components/LoggedOut.tsx, src/lib/LoginState.tsx, src/styles/Main.css
- [] 문서 수정
- 로그인에 따른 헤더 UI 변경
- zustand로 로그인 상태를 관리
- 푸터의 리렌더링을 방지하고자 상수를 컴포넌트 외부로 배치
- 로그아웃 구현
resolves #153
=> [MERGE] : 헤더 푸터 수정 사항 변경(중간 점검 이슈도 해결)

src/layout/Header/components/HeaderSearchBar.module.css, src/layout/Header/components/HeaderSearchBar.tsx, src/lib/SearchState.tsx, src/pages/CardList/components/CardListContainer.tsx, src/pages/Main/Page.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 검색 기능 구현
- 현재 문제 카드 제목에 검색어가 포함되어있다면 렌더링
- zustand로 검색 상태를 공유(Header와 카드 리스트가 상태 공유)
resolves #157
=> [MERGE] : 검색 기능 구현

src/lib/ResetState.tsx
- [] 새로운 기능 추가
- [] 문서 수정
- quiz-complete를 가진 주소를 인식하여 초기화 이벤트 방지
- useEffect로 location.href가 변화될 때 마다 감지
resolves #160
=> [MERGE] : 문제 상태 초기화 오류 수정 후 병합

src/pages/CardCreate/Page.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
문제 생성 페이지에서 supabase에 카드 등록 가능
문제 생성 페이지에서 supabase에 문제 등록 가능
카드 등록 시 hot toast로 성공 메세지 띄우기
<이슈해결>
외래키 불일치 이슈 : 카드 쪽에 유저 외래키가 잘못 연결되어 있었음
resolves #154
=> 문제 생성 페이지에서 카드, 문제 등록 기능

src/components/Card/BookMark.tsx, src/pages/QuizComplete/Page.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 댓글 불러오기 기능
- 댓글 추가 기능 (DB에 추가 + 즉시 렌더링)
- 좋아요, 북마크 기능 (유지되도록)
- 결과 컴포넌트 점수 렌더링 (맞은 문제 개수, 총 문제 개수)
resolves #123
=> [FEAT] : 문제 풀이 완료 페이지 기능 구현

src/layout/Header/Header.tsx, src/layout/Header/components/LoggedIn.tsx, src/pages/CardList/components/CardListContainer.tsx
- [] 버그 수정
- [] 문서 수정
- 검색된 상태에서 태그 sorting과 최신순 인기순 재정렬
- 로그아웃 시 메인 페이지로 이동
resolves #175
=> [MERGE] : 헤더의 로그아웃과 검색 기능 기능 추가 및 변경

src/pages/SignUp/Page.module.css, src/pages/SignUp/Page.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 필수 체크해제 시 오류메시지 출력
- 전체 동의합니다 클릭시 전체 체크, 1개라도 해제시 전체 동의합니다 체크 해제
resolves #144
=> [FEAT] : 필수 약관 동의

src/layout/Header/components/HeaderSearchBar.tsx, src/pages/CardList/components/CardListContainer.module.css, src/pages/CardList/components/CardListContainer.tsx
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
<이슈> 검색 시 특정 컨테이너의 width가 줄어드는 문제
<해결> 타입스크립트 쪽에 아예 width를 명시함.
resolves #178
=> 검색 시 특정 컨테이너의 width가 줄어드는 문제

src/components/EditProfile/ProfileImage.tsx, src/components/MyPageDiary/MyPageDiary.tsx, src/layout/Header/Header.tsx, src/lib/UserProfileState.tsx
- [] 버그 수정
- [] 문서 수정
- supabase에서 storage에 저장
- png확장자 명과 2MB크기로 이미지 제한
resolves #179
=> [MERGE] : 프로필 이미지 변경 로직 구현

src/components/MyPageDiary/MyPageDiary.tsx, src/pages/LogIn/Page.tsx
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
- 배포 과정 중 id를 찾지 못하는 이슈 해결
resolves #190
=> [MERGE] : 배포 중 id를 찾지 못하는 이슈 해결

src/components/Input/Input.tsx, src/layout/Common.tsx, src/pages/SignUp/Page.module.css, src/pages/SignUp/Page.tsx
- [] 버그 수정
- [] 문서 수정
resolves #183
=> [MODIFY] : sign-up a11y 고려해서 코드 변경

index.html
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #198
=> [FEAT] : meta, favicon 추가

index.html
=> [MODIFY] : meta:og 오류 수정 및 description, image 변경

src/lib/BookmarkState.tsx, src/lib/CalendarState.tsx, src/lib/ProblemModalState.tsx, src/lib/SearchState.tsx
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
- zustand의 정보 저장소가 이름이 겹침에 따라 오류 발생하던 문제 해결
resolves #215
=> [MERGE] : 정보 저장소 이름 겹침으로 인한 오류 수정

src/pages/LogIn/Page.tsx
- [] 버그 수정
- [] 문서 수정
- 기존에 로그인을 해도 계속해서 supabase에 insert하던 문제 해결
- 로그인 시 출석체크한 날짜에 따라 레벨업 차이
resolves #222
=> [MERGE] : 레벨업과 출석체크 로직 구현

.vscode/settings.json, src/components/EditProfile/EditProfile.tsx, src/components/EditProfile/EmailAlarm.tsx, src/pages/EditProfile/Page.tsx
- [] 새로운 기능 추가
- [] 문서 수정
개인 정보 관리 페이지에서 '이메일 알람 설정'의 토글 기능 개선
개인정보페이지, 알람 설정 중 토글이 on/off로 변경되지 않는 이슈
resolves #225
=> [MODIFY] : 개인정보관리 페이지, 토글 기능 개선

index.html, src/pages/Badge/Page.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
- title태그와 meta 태그 설정
resolves #229
=> [MODIFY] : title과 meta 태그 설정

index.html, src/components/CardModal/CardModal.tsx, src/pages/Badge/Page.tsx, src/pages/Bookmark/Page.tsx, src/pages/Calendar/Page.tsx, src/pages/CardCreate/Page.tsx, src/pages/CardList/Page.tsx, src/pages/CardWritten/Page.tsx, src/pages/EditProfile/Page.tsx, src/pages/FindId/Page.tsx, src/pages/FindPassword/Page.tsx, src/pages/LogIn/Page.tsx, src/pages/Main/Page.tsx, src/pages/QuizComplete/Page.tsx, src/pages/QuizPlay/Page.tsx, src/pages/RecentView/Page.tsx, src/pages/SignUp/Page.tsx
- [] 버그 수정
- [] 문서 수정
- 메타, 타이틀 태그 추가
- a 태그 NavLink로 변환
- 로그인 하지 않고 접근 불가능한 영역은 meta태그 설정 X
resolves #229
=> [MERGE] : 메타, 타이틀 태그 추가 및 세부적인 내용 수정

src/layout/Footer/Footer.module.css, src/layout/Footer/Footer.tsx, src/layout/Header/Header.module.css, src/pages/LogIn/Page.tsx, src/pages/QuizPlay/components/Quiz.module.css
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
- 헤더 너비 수정
- 헤더 높이 수정
- 푸터 링크 수정
- 푸터 min-width 수정
resolves #237
=> [MERGE] : 헤더 푸터 회의 중 나온 이슈 사항 정리

src/layout/Header/components/LoggedIn.module.css
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- z-index 조절
- 헤더가 변함에 따라 위치 재조정
resolves #131
=> [MERGE] : 마이페이지,로그인 박스 위치 조정

src/components/CardGrid/CardGrid.tsx, src/components/CardSwiper/CardSwiper.tsx, src/components/Skeleton/Skeleton.module.css, src/components/Skeleton/Skeleton.tsx, src/pages/CardList/components/CardListContainer.tsx, src/pages/Main/Page.tsx
- [] 버그 수정
- [] 문서 수정
- 메인 페이지, 마이 페이지, 카드 목록 페이지에 스켈레톤 UI 적용
- 현재는 데이터가 렌더링이 되면 바로 교체되므로 확인하고 싶으면 추후에 강제적으로 delay타임을 추가
resolves #241
=> [MERGE] : 스켈레톤 UI 적용

src/pages/CardList/components/CardListContainer.tsx, src/pages/LogIn/Page.tsx, src/pages/Main/Page.tsx
- [] 새로운 기능 추가
- [] 문서 수정
- 메인 페이지와 문제 목록 페이지 초기 렌더링 안되는 이슈 해결
resolves #247
=> [MERGE] : 문제 스와이퍼 초기 렌더링 이슈 해결

src/pages/Bookmark/Page.tsx, src/pages/RecentView/Page.tsx
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
- 마이페이지에 존재하는 카드에 북마크가 제대로 표시되지 않는 오류 해결
resolves #253
=> [MERGE] : 마이페이지에 북마크가 제대로 표시되지 않는 오류 해결

vite.config.ts
- JS 번들 크기 축소
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
- 중간 점검 개선사항 이슈 적용
resolves #249
=> [REFACTOR] : vite.config.ts 파일 수정

src/pages/FindPassword/Page.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #234
=> [FEAT] : sweetalert2 추가와 변경 성공시 로그인 페이지로 이동

src/components/Card/Card.tsx, src/components/CardModal/CardModal.module.css, src/components/CardModal/CardModal.tsx, src/components/EditProfile/EditProfile.module.css, src/lib/ProblemModalState.tsx, src/lib/ReloadState.tsx, src/pages/Bookmark/Page.tsx, src/pages/CardList/components/CardListContainer.tsx, src/pages/CardWritten/Page.tsx, src/pages/Main/Page.tsx, src/pages/RecentView/Page.tsx
- [] 버그 수정
- [] 문서 수정
- 카드를 작성한 유저라면 풀기 대신 삭제 버튼 활성화
- 삭제 시 리렌더링 발생
resolves #251
=> [MERGE] : 카드 삭제 기능 구현

src/pages/EditProfile/Page.tsx, src/pages/QuizPlay/components/Quiz.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 단순 이미지 교체
resolves #259
=> [MERGE] : 오답 시 해파리 출력 이미지 변경

src/pages/CardCreate/Page.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 단순 페이지 이름 변경
resolves #261
=> [MERGE] : 카드 생성 텍스트 변경

src/layout/Header/Header.tsx, src/layout/Header/components/HeaderSearchBar.tsx, src/layout/Header/components/LoggedIn.tsx, src/pages/CardCreate/components/QuizCreate.tsx, src/pages/EditProfile/Page.tsx, src/pages/FindPassword/Page.tsx, src/pages/QuizComplete/Page.tsx, src/pages/QuizComplete/components/InputBox.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #240
=> [MERGE] : import 구문 내림차순 정렬

src/pages/QuizComplete/Page.module.css, src/pages/QuizComplete/components/InputBox.module.css
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 공백 축소
- InputBox 컴포넌트 CSS 수정
resolves #257
=> [MERGE] : 문제 풀이 완료 페이지 CSS 수정

src/styles/Main.css
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- main.css 에 존재하는 bookmark 색상 변경(명도에 맞춰서)
resolves #273
=> [MERGE] : bookmark 색상을 명도에 맞게 변경

public/robots.txt, src/lib/ResetState.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
- robots.txt 추가로 SEO 개선
- 화면 이동 시 window.scrollTop(0,0)으로 항상 상단을 보여주기
resolves #279
=> [MERGE] : SEO 개선 및 UX 개선

src/components/Card/BookMark.tsx, src/components/EditProfile/ProfileImage.tsx, src/components/QuizResult/QuizResult.tsx, src/lib/QuizSolvedState.tsx, src/pages/QuizComplete/Page.tsx, src/pages/QuizComplete/components/InputBox.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
- 웹 표준 및 접근성을 위한 리팩토링
resolves #224
=> [MERGE] : 문제 풀이 완료 페이지 리팩토링

src/pages/EditProfile/Page.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
코드 정리 및 주석 추가
resolves #284
=> [REFACTOR] : 주석 달기 및 코드 정리
